name: homeprint_o_tool
description: A tool to arrange individual card images with bleed into double-sided uncut sheets.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.5
  uuid: ^4.5.1
  path: ^1.8.3
  widgets_to_image: any
  image: ^4.1.7
  file_selector: ^1.0.3
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true