name: homeprint_o_tool
description: A tool to arrange individual card images with bleed into double-sided uncut sheets.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.5
  file_picker: ^5.3.3
  uuid: ^3.0.7
  path: ^1.8.3
  widgets_to_image: any
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true